### ISSUE TITLE
Unable to serve rails apps

### ISSUE THREAD

**Issue by maximedupre** [mices/rails_6_chat_app#1]
Failed to connect to localhost port 9200: Connection refused (Faraday::ConnectionFailed

**Comment by mices** [comment]
Sorry I forgot to remove references to elasticsearch from models

**Comment by maximedupre** [comment]
I think you'll also have to remove any notion of a db. When accessing `http://localhost:3000/`:

![Screen Shot 2020-01-27 at 12 15 30 PM](https://user-images.githubusercontent.com/5158181/73197085-bcb3eb00-40fe-11ea-8ecd-3438063aa69b.png)

**Comment by mices** [comment]
You have to install mysql-server With mysql installed you would have to create the databases, grant permissions to your username, run rails db:schema:load which will create tables from the schema.rb file
sudo mysql
create database rails_6_chat_app;
grant all privileges on rails_6_chat_app_development.* to 'mices'@'localhost' identified by 'password';
exit
cd /home/mices/rails_6_chat_app
bundle
rails db:schema:load

**Comment by maximedupre** [comment]
In the console after running `rails db:schema:load`:

    rails aborted!
    Mysql2::Error::ConnectionError: Can't connect to local MySQL server through socket 
    '/var/run/mysqld/mysqld.sock' (2)

I can see the "rails_6_chat_app" db in MySQLWorkbench, though. I also tried changing  `config/database.yml` to use my `root` user and password, to no avail.

**Comment by mices** [comment]
So then mysqld.sock is in another folder Can you try to find the path to the file maybe it's  /usr/sbin/mysqld/mysqld.sock then update database.yml

**Comment by maximedupre** [comment]
Had to make the following changes:

    default: &default
      adapter: mysql2
      port: 3306
      encoding: utf8
      pool: 5
      socket: /tmp/mysql.sock


    development:
      <<: *default
      database: rails_6_chat_app
      username: root
      password: mypass
      socket: /tmp/mysql.sock

But somehow rails won't connect to my DB using the password I provided:

    rails aborted!
    Mysql2::Error::ConnectionError: Access denied for user 'root'@'localhost' (using password: NO)

How do I tell rails to use my password?

**Comment by mices** [comment]
at the mysql prompt you have to 
grant all privileges on rails_6_chat_app_development.* to 'user'@'localhost' identified by 'password'
replace user with a user on your system other than root

**Comment by maximedupre** [comment]
When signing up:

![Screen Shot 2020-01-27 at 9 13 26 PM](https://user-images.githubusercontent.com/5158181/73230084-07a72000-414a-11ea-8186-dd5ef0d26013.png)

**Comment by mices** [comment]
This runs ok for me on ruby 2.6.5 You may have to delete the file Gemfile.lock and run `gem install bundler` and then `bundle install`

**Comment by mices** [comment]
It seems part of the problem, the reason the image doesn't display until page refresh or redirect to same page is that javascript is appending a url to the image to the dom element but that isn't enough to cause the image to render yet It seems the only solution is to send append a link to the image to the dom element instead of an <img src=" ..."> tag

**Comment by maximedupre** [comment]
I'm also using ruby 2.6.5.

> You may have to delete the file Gemfile.lock and run gem install bundler and then bundle install

Did that, but I still got the error when signing up. I looked in the DB though, and the user is still created. I added values in the `confirmed_at`  columns of my users to be able to log in.  However, when trying to log in: 

![Screen Shot 2020-01-28 at 8 50 52 AM](https://user-images.githubusercontent.com/5158181/73269706-546f1300-41ab-11ea-8b63-f0dc5dbe8577.png)

**Comment by mices** [comment]
This is another database issue You're trying to use TRADITIONAL sql_mode but mysql is using STRICT You have to edit /etc/mysql/mysql.conf.d/mysqld.cnf and under [mysqd] put sql_mode="TRADITIONAL"

**Comment by maximedupre** [comment]
Ok I got to login successfully, but can't seem to access the specific chat route.

    No route matches [GET] "/chats/maxwell"

I tried to access this route from one browser, where the user logged in is "john". The user "maxwell" is logged in in the other browser.

**Comment by maximedupre** [comment]
How is your application supposed to work? If I send a message on one browser, is it supposed to appear on the other browser? I don't see messages being sent to the other browser.

Chrome: User is "john" at url  /chats/maxwell
Firefox:   User is "maxwell" at url  /chats/john

Sending a message from either browser has no effect on the other browser.

**Comment by mices** [comment]
Yes there was some non-working code Please refork

**Comment by maximedupre** [comment]
`ActiveRecord::StatementInvalid (Mysql2::Error: Table 'rails_6_chat_app.taggings' doesn't exist):`

**Comment by mices** [comment]
I removed acts_as_taggable from app/models/message.rb Please try again

**Comment by mices** [comment]
Please refork I removed acts_as_taggable from app/models/message.rb and made some changes to app/javascript/channels/room_channel.rb

**Comment by maximedupre** [comment]
So I see that when I post an image, it does not appear in your container div. Can you explain to me what is the problem with Trix? The Trix editor seems to be working fine to me.

**Comment by maximedupre** [comment]
Most likely the problem has to do with how Rails treats the request params. For example, in `messages_controller.rb`, if you do a `puts` of `message_params.content` in the `create` action, it will show Trix's original content, with a `div` element, a `figure` element and an `img` element.

If instead, you do a `puts` of `@message.content`, you will see a modified version of the Trix payload, containing a `div`, a `action-text-attachment`, an `img` and a `figcaption`.

Furthermore, if you check `data.content.body` in your `room_channel.js`, you will see that it contains a partial representation of the modified HTML. It contains only the `div`, and the `action-text-attachment`.

Please close the ticket on the Trix github repo, as this is not a Trix issue. Perhaps you could log a ticket on the Rails repo if you think there is a bug.

**Comment by mices** [comment]
Yes I had already found that the problem's not related to trix By using raw activestorage methods I have to deal with attachments separately I thought trix would be easier The issue raises the question how can I use trix in actioncable chat

**Comment by maximedupre** [comment]
Right. Since it modifies any HTML, Trix is irrelevant - the HTML could come from anywhere. So the issue is how can you use any HTML containing a `figure` and an `img` element and raw activestorage methods. But I understand it happens that you encountered this problem with the HTML that was provided with Trix. I think you are better suited than me to solve your particular, rails-specific problem. Cheers!
